name: Python

on:
  push:
    branches:
      - "main"
    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install Python dependencies
        run: | 
          python -m pip install --upgrade pip requests
          pip install requests
          pip install pandas
          pip install discord.py

      - name: Execute Python script 
        run:  python3 ./python/app.py